### PR TITLE
Remove the UpdateProperty Adapter component

### LINKED ISSUE #148: Remove the UpdateProperty component
#### Broken rules:

As per https://github.com/BHoM/BHoM_Adapter/issues/109#issuecomment-545982080

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Adapter/pull/151

   
### Issues addressed by this PR

As per https://github.com/BHoM/BHoM_Adapter/issues/109
removed the UpdateProperty component.

Closes #148

### CODE REVIEW

File: BHoM_UI/Global/SearchMenu.cs [hunk 1]
```diff
@@ -92,7 +92,6 @@ protected virtual List<SearchItem> GetAllPossibleItems()
                 new SearchItem { Item = typeof(MoveCaller).GetMethod("Move"), CallerType = typeof(MoveCaller), Icon = Properties.Resources.Move },
                 new SearchItem { Item = typeof(PullCaller).GetMethod("Pull"), CallerType = typeof(PullCaller), Icon = Properties.Resources.Pull },
                 new SearchItem { Item = typeof(PushCaller).GetMethod("Push"), CallerType = typeof(PushCaller), Icon = Properties.Resources.Push },
-                new SearchItem { Item = typeof(UpdatePropertyCaller).GetMethod("UpdateProperty"), CallerType = typeof(UpdatePropertyCaller), Icon = Properties.Resources.UpdateProperty },
```
Comment (adecler) [inline BHoM_UI/Global/SearchMenu.cs]: This is clashing with an pre-existing PR: https://github.com/BHoM/BHoM_UI/pull/147
