### PR TITLE
Ensuring immutability for SetProperty by deep cloning object

### LINKED ISSUE #226: BHoM_UI: SetPropertyValue is not immutable when tweaking inner objects.
#### Description:

When changing an inner property, such as bar.StartNode.Name, the input item is changed as well as the output. this causes weird behaviours in visual programming setups. Will be even more problematic if the values are scaled, as re-running the script then will keep on scaling.

#### Steps to reproduce:

Set a inner property of an object, then check the values of the upstream object.

#### Expected behaviour:

For only the output objects to be changed.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/Es1XVgVIo6xAqXPRZyndtbkBv89NqlXKMUkRutdRaWHNSw?e=zpHf64

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #226 

Deep clone input to have its property set to make sure the input does not get changed.

This was causing issues when multiple layer property set was being used, causing the upstream obejcts to be changed.

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Es1XVgVIo6xAqXPRZyndtbkBv89NqlXKMUkRutdRaWHNSw?e=zpHf64

### CODE REVIEW

File: BHoM_UI/Components/Engine/SetProperty.cs [hunk 1]
```diff
@@ -108,6 +109,16 @@ protected override void CompileInputGetters()
                 base.CompileInputGetters();
         }
 
+        /*************************************/
+
+        public override object Run(object[] inputs)
+        {
+            if (inputs != null && inputs.Length >= 1 && inputs[0] != null)
+            {
+                inputs[0] = inputs[0].DeepClone();
```
Comment (alelom) [inline BHoM_UI/Components/Engine/SetProperty.cs]: Maybe add a comment
```cs
// Deepclone must be done before the properties are set to ensure immutability
```
and something else to explain why it has to be done at the UI level instead than in the Engine perhaps?

Comment (al-fisher) [reply BHoM_UI/Components/Engine/SetProperty.cs]: Yeah - good idea

Comment (adecler) [reply BHoM_UI/Components/Engine/SetProperty.cs]: LGTM. Agreed with @alelom

**Comment by IsakNaslundBh** [comment]
@alelom comment added if you could re-review
